version: "3"
services:
  db:
    container_name: db-inventory-management
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_MULTIPLE_DATABASES: inventory_management,inventory_management_test
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./backend/database/postgres/data:/docker-entrypoint-initdb.d
    networks:
      - inventory-management
    restart: always

networks:
  inventory-management:
    driver: bridge