version: "3"
services:
  db:
    container_name: db-inventory-management
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_MULTIPLE_DATABASES: inventory_management,inventory_management_test
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./backend/database/postgres:/docker-entrypoint-initdb.d
      - ./backend/database/postgres/data:/var/lib/postgresql/data
    networks:
      - inventory-management
    restart: always
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./backend/database/elasticsearch/data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - inventory-management
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./backend/database/elasticsearch/data02:/usr/share/elasticsearch/data
    networks:
      - inventory-management
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./backend/database/elasticsearch/data03:/usr/share/elasticsearch/data
    networks:
      - inventory-management

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
networks:
  inventory-management:
    driver: bridge