version: "3"
services:
  db:
    container_name: db-inventory-management
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_MULTIPLE_DATABASES: inventory_management,inventory_management_test
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./backend/database/postgres:/docker-entrypoint-initdb.d
      - ./backend/database/postgres/data:/var/lib/postgresql/data
    networks:
      - inventory-management
    restart: always
  elastic_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
    container_name: es01
    environment:
      - discovery.type=single-node
      - node.name=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./backend/database/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - inventory-management
    restart: always

volumes:
  data:
    driver: local
networks:
  inventory-management:
    driver: bridge