root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./application.exe ./cmd/server/main.go"
bin = "application.exe"
full_bin = "application.exe"
include_ext = ["go", "tpl", "tmpl", "html", "mustache", "hbs", "pug"]
exclude_dir = ["tmp"]
include_dir = []
exclude_file = []
log = "air.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # ms

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true